@file:OptIn(ExperimentalEvscApi::class)

package com.huanshankeji.exposedvertxsqlclient.integrated

import arrow.core.Either
import arrow.core.left
import arrow.core.right
import com.huanshankeji.exposedvertxsqlclient.DatabaseClient
import com.huanshankeji.exposedvertxsqlclient.ExperimentalEvscApi
import com.huanshankeji.exposedvertxsqlclient.crud.insert
import io.kotest.matchers.shouldBe
import io.vertx.sqlclient.SqlClient
import io.vertx.sqlclient.SqlConnection
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.jdbc.Query
import org.jetbrains.exposed.v1.jdbc.select

// adapted from some examples generated by Copilot

internal fun selectExampleNameWhereEqQuery(name: String): Query =
    with(Examples) { select(this.name).where(this.name eq name) }

abstract class CommonTransactionOrRollbackTests<VertxSqlClientT : SqlClient>(
    val databaseClient: DatabaseClient<VertxSqlClientT>
) {
    // The `DatabaseClient` receiver has to be passed explicitly because the transaction clients should be passed.
    protected suspend fun DatabaseClient<*>.insertExampleWithName() =
        insert(Examples) { it[name] = "name" }

    // On the contrary.
    protected suspend fun getExamplesWithNameSize() =
        databaseClient.executeQuery(selectExampleNameWhereEqQuery("name")).size()
}

class TransactionOrRollbackEitherTests<VertxSqlClientT : SqlClient/*, SqlConnectionT : SqlConnection*/>(
    databaseClient: DatabaseClient<VertxSqlClientT>,
    val withTransactionOrRollback: suspend DatabaseClient<VertxSqlClientT>.(function: suspend (DatabaseClient<SqlConnection>) -> Either<Unit, Unit>) -> Either<Unit, Unit>
) : CommonTransactionOrRollbackTests<VertxSqlClientT>(databaseClient) {
    suspend fun testSuccess() {
        databaseClient.withTransactionOrRollback { databaseClient ->
            databaseClient.insertExampleWithName()
            Unit.right()
        }

        // Verify data was committed
        getExamplesWithNameSize() shouldBe 1
    }

    suspend fun testExplicitRollback() {
        databaseClient.withTransactionOrRollback { databaseClient ->
            databaseClient.insertExampleWithName()
            Unit.left()
        }

        // Verify data was rolled back
        getExamplesWithNameSize() shouldBe 0
    }

    suspend fun testOnException() {
        // Test that exception causes rollback
        try {
            databaseClient.withTransactionOrRollback { databaseClient ->
                databaseClient.insertExampleWithName()
                throw RuntimeException()
                //Unit.right()
            }
        } catch (_: RuntimeException) {
        }

        // Verify data was rolled back
        getExamplesWithNameSize() shouldBe 0
    }
}

class TransactionOrRollbackTests<VertxSqlClientT : SqlClient>(
    databaseClient: DatabaseClient<VertxSqlClientT>,
    val withTransactionOrRollback: suspend DatabaseClient<VertxSqlClientT>.(function: suspend (DatabaseClient<SqlConnection>) -> Unit) -> Unit
) : CommonTransactionOrRollbackTests<VertxSqlClientT>(databaseClient) {
    suspend fun testSuccess() {
        databaseClient.withTransactionOrRollback { databaseClient ->
            databaseClient.insertExampleWithName()
        }

        // Verify data was committed
        getExamplesWithNameSize() shouldBe 1
    }

    suspend fun testOnException() {
        // Test that exception causes rollback
        try {
            databaseClient.withTransactionOrRollback { databaseClient ->
                databaseClient.insertExampleWithName()
                throw RuntimeException()
            }
        } catch (_: RuntimeException) {
        }

        // Verify data was rolled back
        getExamplesWithNameSize() shouldBe 0
    }
}
